services:
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AceRental@2026!
    ports:
      - "1433:1433"
    networks:
      - gatewayAceRental
  identityserver:
    # container_name: acerental-identityserver
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: ./src
      dockerfile: AceRental.IdentityServer/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_URLS=http://+:8080
      # Si IdentityServer a besoin d'une BDD, ajoutez la chaîne de connexion ici
    ports:
      - "5001:5001"
    networks:
      - gatewayAceRental
  acerental-api:
    # container_name: acerental-api
    image: ${DOCKER_REGISTRY-}acerentalapi
    build:
      context: ./src
      dockerfile: AceRental.Api/Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - gatewayAceRental
  acerental-frontend:
    # container_name: acerental-frontend
    image: ${DOCKER_REGISTRY-}acerentalfrontend
    build:
      context: ./AceRental.FrontEnd
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:3000
      - ASPNETCORE_ENVIRONMENT=Development
      - FrontUrl=http://acerental-angular:4200
    ports:
      - "3000:3000"
    networks:
      - gatewayAceRental
  acerental-angular:
    # container_name: acerental-angular
    image: ${DOCKER_REGISTRY-}acerentalangular
    build:
      context: ./AceRental.FrontEnd
      dockerfile: ClientApp/Dockerfile
    ports:
      - "4200:4200"
    networks:
      - gatewayAceRental

networks:
    gatewayAceRental: {}
