@Api_HostAddress = http://localhost:5000

### Create Client
POST {{Api_HostAddress}}/Api/v1/Clients/
Content-Type: application/json

{
}


### Get Client
GET {{Api_HostAddress}}/Api/v1/Clients?$filter=Id eq 3fa85f64-5717-4562-b3fc-2c963f66afa6&$expand=Reservations
Content-Type: application/json

### Get Client
GET {{Api_HostAddress}}/Api/v1/Clients(3fa85f64-5717-4562-b3fc-2c963f66afa6)?$expand=Reservations
Content-Type: application/json

### Get All Clients
GET {{Api_HostAddress}}/api/v1/Clients?$expand=Reservations
Content-Type: application/json

