@Api_HostAddress = http://localhost:5000

### Create Client
POST {{Api_HostAddress}}/Api/v1/Clients/
Content-Type: application/json

{
  "reference": "ART315",
  "name": "RCF ART 315",
  "description": "Enceinte rcf art315",
  "dailyPrice": 50,
  "purchasePrice": 500,
  "newPurchasePrice": 1000,
  "totalStock": 2,
  "category": 0
}


### Get Equipment
GET {{Api_HostAddress}}/Api/v1/Equipments/821423d3-a472-491d-9886-42c20134285a
Content-Type: application/json

### Get All Equipment
GET {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

