@Api_HostAddress = http://localhost:5000
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFNjYyMTgyNzkxMzM4NEQyNzlFOUFFNUM0N0FBQkJBIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJuYmYiOjE3ODE3OTMzMDMsImlhdCI6MTc4MTc5MzMwMywiZXhwIjoxNzgxNzk2OTAzLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiLCJhcGkiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJhY2UtcmVudGFsLWFuZ3VsYXIiLCJzdWIiOiIzMDcwOTlhNi1hNGQxLTRhZmMtOTExMi00NDZiYWE0M2Y3ZTgiLCJhdXRoX3RpbWUiOjE3ODE3ODU1NTksImlkcCI6ImxvY2FsIiwiZW1haWwiOiJoYXRlbWJlZGRhaXJhQGdtYWlsLmNvbSIsIm5hbWUiOiJEYWlyYSBIYXRlbSIsInJvbGUiOiJBZG1pbiIsInNpZCI6IkY5MDVBMThDRTc0NzMwRjgyNDhEN0MxRkU1MEEwQTJBIiwianRpIjoiNTc5RjA3QUY4NDg3RjZCRTg3NzlDNkRFMzQ2QTRCQTkifQ.b23xuojO3zL5HHgI6TEsYINxQMmzOjLVNzTbbirCoca35S98-cbzojLENoYsJyr6LI7H8YuMk4HZMHYpHChiUVMs0sxWVi69wGl_uMo_rne8ohhPl0T3rWKtftmPVe2frOftkGaFxeEhabYC1p0zE1S-RTVujquTFA6eAGqvp8FXYea4aW9a5Vmq4-J5eoqXp3kGws8kCEwZxU37nBoBkegesVPDus_sdjJhAO1qPtBSH3bF5Eka9oj6_2fcSoMZwNvcnhrP7QhQmpHubljxFwU_zTPi0LedqRCE-vxLo5592-C22Dvy10zTrbC4vs4HoC-kqvsT_Hfv1rmLZXgqQw

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "ART315",
  "name": "RCF ART 315",
  "description": "Enceinte rcf art315",
  "dailyPriceHT": 50,
  "purchasePrice": 500,
  "newPurchasePrice": 1000,
  "totalStock": 2,
  "category": 0
}


### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "W400a",
  "name": "Montarbo W400a",
  "description": "Enceinte Montarbo W400a",
  "dailyPriceHT": 50,
  "purchasePrice": 500,
  "newPurchasePrice": 1000,
  "totalStock": 2,
  "category": 0
}

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "DSR115",
  "name": "Yamaha DSR115",
  "description": "Enceinte yamaha dsr115",
  "dailyPriceHT": 75,
  "purchasePrice": 750,
  "newPurchasePrice": 1600,
  "totalStock": 2,
  "category": 0
}

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "DSR112",
  "name": "Yamaha DSR112",
  "description": "Enceinte yamaha dsr112",
  "dailyPriceHT": 50,
  "purchasePrice": 500,
  "newPurchasePrice": 1000,
  "totalStock": 4,
  "category": 0
}

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "mg24",
  "name": "Yamaha MG24",
  "description": "Console analogique yamaha mg24",
  "dailyPriceHT": 50,
  "purchasePrice": 500,
  "newPurchasePrice": 1600,
  "totalStock": 4,
  "category": 0
}

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "M32R",
  "name": "Midas M32R",
  "description": "Console numérique midas m32r",
  "dailyPriceHT": 120,
  "purchasePrice": 1600,
  "newPurchasePrice": 2500,
  "totalStock": 1,
  "category": 0
}

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "DSR118",
  "name": "Yamaha DSR118",
  "description": "Caisson de basse yamaha dsr118",
  "dailyPriceHT": 75,
  "purchasePrice": 800,
  "newPurchasePrice": 1600,
  "totalStock": 2,
  "category": 0
}

### Create Equipment
POST {{Api_HostAddress}}/Api/v1/Equipments/
Content-Type: application/json

{
  "reference": "JETS",
  "name": "Jets scène",
  "description": "jets scène",
  "dailyPriceHT": 15,
  "purchasePrice": 0,
  "newPurchasePrice": 0,
  "totalStock": 200,
  "category": 0
}


### Get Equipment
GET {{Api_HostAddress}}/Api/v1/Equipments?$filter=Id eq b79d3481-df2c-4287-a340-01d4c7a86edd&$expand=Packs
Content-Type: application/json

### Get Equipment
GET {{Api_HostAddress}}/Api/v1/Equipments(1cf8e37e-52a2-47e7-9973-910262aae973)?$expand=Packs
Content-Type: application/json

### Get All Equipment
GET {{Api_HostAddress}}/api/v1/Equipments?$expand=Packs
Content-Type: application/json
Authorization: Bearer {{token}}


### Get Availability
GET {{Api_HostAddress}}/api/v1/Equipments/Availability(id=c71beabe-518f-4da0-ac38-442df3319720,startDate=2025-02-02,endDate=2025-02-03)
Content-Type: application/json
