@Api_HostAddress = http://localhost:5000

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json

{
  "reference": "SOL",
  "name": "Pack SOL",
  "description": "Pack de deux enceintes en facade et deux retours et une console analogique",
  "dailyPriceHT": 300,
  "items": [
    {
      "equipmentId": "20ff66f9-323a-487b-afcc-ded80b101866",
      "quantity": 2   
    },
    {
      "equipmentId": "0394d635-58d3-4e34-8ff6-4f963ebcbd97",
      "quantity": 2      
    },
    {
      "equipmentId": "9285e5bf-a47c-4c46-aeed-872eb73788c1",
      "quantity": 1      
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json

{
  "reference": "RE",
  "name": "Pack RE",
  "description": "Pack de deux enceintes en facade, quatres retours et une console analogique",
  "dailyPriceHT": 400,
  "items": [
    {
      "equipmentId": "20ff66f9-323a-487b-afcc-ded80b101866",
      "quantity": 2   
    },
    {
      "equipmentId": "0394d635-58d3-4e34-8ff6-4f963ebcbd97",
      "quantity": 4      
    },
    {
      "equipmentId": "9285e5bf-a47c-4c46-aeed-872eb73788c1",
      "quantity": 1      
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json

{
  "reference": "DO",
  "name": "Pack DO",
  "description": "Pack de deux enceintes en facade, deux caissons de basse, quatres retours et une console analogique",
  "dailyPriceHT": 550,
  "items": [
    {
      "equipmentId": "20ff66f9-323a-487b-afcc-ded80b101866",
      "quantity": 2   
    },
    {
      "equipmentId": "0394d635-58d3-4e34-8ff6-4f963ebcbd97",
      "quantity": 4      
    },
    {
      "equipmentId": "9285e5bf-a47c-4c46-aeed-872eb73788c1",
      "quantity": 1      
    },
    {
      "equipmentId": "a224731d-4c50-415c-8ec0-b3d7b689d221",
      "quantity": 2      
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json

{
  "reference": "SOL",
  "name": "Pack SOL",
  "description": "Pack de deux enceintes en facade et trois retours",
  "dailyPriceHT": 400,
  "items": [
    {
      "equipmentId": "06090152-518d-4b93-8c80-9df8d5e9eb0b",
      "quantity": 2   
    },
    {
      "equipmentId": "79a9457b-0cb7-42e3-944a-66c11902f643",
      "quantity": 3      
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json

{
  "reference": "RE",
  "name": "Pack RE",
  "description": "Pack de deux enceintes en facade et deux retours",
  "dailyPriceHT": 300,
  "items": [
    {
      "equipmentId": "06090152-518d-4b93-8c80-9df8d5e9eb0b",
      "quantity": 2   
    },
    {
      "equipmentId": "79a9457b-0cb7-42e3-944a-66c11902f643",
      "quantity": 2      
    }
  ]
}

### Get Pack
GET {{Api_HostAddress}}/Api/v1/Packs/821423d3-a472-491d-9886-42c20134285a
Content-Type: application/json

### Get All Pack
GET {{Api_HostAddress}}/Api/v1/Packs?$expand=Items($expand=Equipment)
Content-Type: application/json

