@Api_HostAddress = http://localhost:5000
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IkJFNjYyMTgyNzkxMzM4NEQyNzlFOUFFNUM0N0FBQkJBIiwidHlwIjoiYXQrand0In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJuYmYiOjE3ODE3OTMzMDMsImlhdCI6MTc4MTc5MzMwMywiZXhwIjoxNzgxNzk2OTAzLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwiZW1haWwiLCJhcGkiXSwiYW1yIjpbInB3ZCJdLCJjbGllbnRfaWQiOiJhY2UtcmVudGFsLWFuZ3VsYXIiLCJzdWIiOiIzMDcwOTlhNi1hNGQxLTRhZmMtOTExMi00NDZiYWE0M2Y3ZTgiLCJhdXRoX3RpbWUiOjE3ODE3ODU1NTksImlkcCI6ImxvY2FsIiwiZW1haWwiOiJoYXRlbWJlZGRhaXJhQGdtYWlsLmNvbSIsIm5hbWUiOiJEYWlyYSBIYXRlbSIsInJvbGUiOiJBZG1pbiIsInNpZCI6IkY5MDVBMThDRTc0NzMwRjgyNDhEN0MxRkU1MEEwQTJBIiwianRpIjoiNTc5RjA3QUY4NDg3RjZCRTg3NzlDNkRFMzQ2QTRCQTkifQ.b23xuojO3zL5HHgI6TEsYINxQMmzOjLVNzTbbirCoca35S98-cbzojLENoYsJyr6LI7H8YuMk4HZMHYpHChiUVMs0sxWVi69wGl_uMo_rne8ohhPl0T3rWKtftmPVe2frOftkGaFxeEhabYC1p0zE1S-RTVujquTFA6eAGqvp8FXYea4aW9a5Vmq4-J5eoqXp3kGws8kCEwZxU37nBoBkegesVPDus_sdjJhAO1qPtBSH3bF5Eka9oj6_2fcSoMZwNvcnhrP7QhQmpHubljxFwU_zTPi0LedqRCE-vxLo5592-C22Dvy10zTrbC4vs4HoC-kqvsT_Hfv1rmLZXgqQw

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "reference": "SOL",
  "name": "Pack SOL",
  "description": "Pack de deux enceintes en facade et deux retours et une console analogique",
  "dailyPriceHT": 300,
  "items": [
    {
      "equipmentId": "fbc5b7ab-f72b-43f3-81a7-0153d78370d3",
      "quantity": 2   
    },
    {
      "equipmentId": "585ed7b6-be73-495c-af22-2af4b8ba7043",
      "quantity": 1      
    },
    {
      "equipmentId": "aa330552-1777-4750-b479-1f68f671badf",
      "quantity": 2    
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "reference": "RE",
  "name": "Pack RE",
  "description": "Pack de deux enceintes en facade, quatres retours et une console analogique",
  "dailyPriceHT": 400,
  "items": [
    {
      "equipmentId": "fbc5b7ab-f72b-43f3-81a7-0153d78370d3",
      "quantity": 2   
    },
    {
      "equipmentId": "6928fb9c-ac4d-4f77-b867-69641ed131b4",
      "quantity": 1      
    },
    {
      "equipmentId": "aa330552-1777-4750-b479-1f68f671badf",
      "quantity": 4    
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "reference": "DO",
  "name": "Pack DO",
  "description": "Pack de deux enceintes en facade, deux caissons de basse, quatres retours et une console analogique",
  "dailyPriceHT": 550,
  "items": [
    {
      "equipmentId": "865f4674-d287-4c5e-83f8-cf2343a77de2",
      "quantity": 2   
    },
    {
      "equipmentId": "585ed7b6-be73-495c-af22-2af4b8ba7043",
      "quantity": 1      
    },
    {
      "equipmentId": "cd08c78c-8d93-4dde-b290-74b4b212c513",
      "quantity": 4   
    },
    {
      "equipmentId": "5fbcde7b-9f9f-4998-bcd7-f1b056d875f7",
      "quantity": 2    
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "reference": "SOL",
  "name": "Pack SOL",
  "description": "Pack de deux enceintes en facade et trois retours et une console analogique",
  "dailyPriceHT": 400,
  "items": [
    {
      "equipmentId": "06090152-518d-4b93-8c80-9df8d5e9eb0b",
      "quantity": 2   
    },
    {
      "equipmentId": "79a9457b-0cb7-42e3-944a-66c11902f643",
      "quantity": 3      
    }
  ]
}

### Create Pack
POST {{Api_HostAddress}}/Api/v1/Packs/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "reference": "RE",
  "name": "Pack RE",
  "description": "Pack de deux enceintes en facade et deux retours et une console analogique",
  "dailyPriceHT": 300,
  "items": [
    {
      "equipmentId": "06090152-518d-4b93-8c80-9df8d5e9eb0b",
      "quantity": 2   
    },
    {
      "equipmentId": "79a9457b-0cb7-42e3-944a-66c11902f643",
      "quantity": 2      
    }
  ]
}

### Get Pack
GET {{Api_HostAddress}}/Api/v1/Packs/821423d3-a472-491d-9886-42c20134285a
Content-Type: application/json
Authorization: Bearer {{token}}

### Get All Pack
GET {{Api_HostAddress}}/Api/v1/Packs?$expand=Items($expand=Equipment)
Content-Type: application/json
Authorization: Bearer {{token}}


