@Api_HostAddress = http://localhost:5000

### Create Reservation
POST {{Api_HostAddress}}/Api/v1/Reservations/
Content-Type: application/json

{
  "clientId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "startDate": "2026-03-07T13:46:30.484Z",
  "endDate": "2026-03-08T13:46:30.484Z",
  "workflow": 0,
  "items": [
    {
      "packId": "a766f425-7963-4d82-8c48-9a9d819b4c0e",
      "quantity": 1   
    },
    {
      "equipmentId": "cf7b4f49-3a49-4c89-9624-2dca5f87def7",
      "quantity": 2      
    }
  ]
}


### Update Reservation Date and qte
PUT {{Api_HostAddress}}/Api/v1/Reservations/
Content-Type: application/json

{
  "reservationId": "8e8a5dae-efde-47f1-be21-44517591b554",
  "startDate": "2026-03-20T13:46:30.484Z",
  "endDate": "2026-03-21T13:46:30.484Z",
  "items": [
    {
      "packId": "a766f425-7963-4d82-8c48-9a9d819b4c0e",
      "quantity": 1   
    },
    {
      "equipmentId": "cf7b4f49-3a49-4c89-9624-2dca5f87def7",
      "quantity": 1      
    }
  ]
}

### Update Reservation qte
PUT {{Api_HostAddress}}/Api/v1/Reservations/
Content-Type: application/json

{
  "reservationId": "9ec151df-6b25-445d-8dc3-f47b9234c7ff",
  "startDate": "2026-03-07T13:46:30.484Z",
  "endDate": "2026-03-08T13:46:30.484Z",
  "status": 1,
  "items": [
    {
      "packId": "807fa5c0-48de-4966-8dc1-404925f96f91",
      "quantity": 3   
    },
    {
      "equipmentId": "11c6602f-73ae-4ec1-9bcb-e6ec6734f492",
      "quantity": 2      
    }
  ]
}


### Get Reservation
GET {{Api_HostAddress}}/Api/v1/Reservations/8e8a5dae-efde-47f1-be21-44517591b554
Content-Type: application/json

### Get All Reservation
GET {{Api_HostAddress}}/Api/v1/Reservations/
Content-Type: application/json

