@Api_HostAddress = http://localhost:5149

### Create Reservation
POST {{Api_HostAddress}}/Api/v1/Reservations/
Content-Type: application/json

{
  "clientId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "startDate": "2026-03-09T13:46:30.484Z",
  "endDate": "2026-03-10T13:46:30.484Z",
  "workflow": 1,
  "packs": [
    {
      "packId": "fe70da20-d25a-411b-9e52-9055481ef31d",
      "quantity": 1   
    }
  ],
  "equipments": [
    {
      "equipmentId": "41f64f47-41b0-4dfc-ab45-1f3cf1187516",
      "quantity": 2      
    }
  ],
  "services": [
    {
      "serviceId": "3b1102cc-1551-47c9-aca0-9704d0311067",
      "quantity": 1      
    },
    {
      "serviceId": "70e79e28-4a97-439c-abe5-5fdbdbf9ff55",
      "quantity": 1      
    }
  ]
}


### Update Reservation Date and qte
PATCH {{Api_HostAddress}}/Api/v1/Reservations(083410ba-9fce-4539-9d94-beabbd212dba)
Content-Type: application/json

{
  "startDate": "2026-03-20T13:46:30.484Z",
  "endDate": "2026-03-21T13:46:30.484Z",
  "packs": [
    {
      "packId": "fe70da20-d25a-411b-9e52-9055481ef31d",
      "quantity": 1   
    }
  ],
  "equipments": [
    {
      "equipmentId": "41f64f47-41b0-4dfc-ab45-1f3cf1187516",
      "quantity": 1      
    }
  ],
  "services": [
    {
      "serviceId": "3b1102cc-1551-47c9-aca0-9704d0311067",
      "quantity": 1      
    },
    {
      "serviceId": "70e79e28-4a97-439c-abe5-5fdbdbf9ff55",
      "quantity": 1      
    }
  ]
}

### Update Reservation qte
PATCH {{Api_HostAddress}}/Api/v1/Reservations(083410ba-9fce-4539-9d94-beabbd212dba)
Content-Type: application/json

{
  "packs": [
    {
      "packId": "fe70da20-d25a-411b-9e52-9055481ef31d",
      "quantity": 1   
    }
  ],
  "equipments": [
    {
      "equipmentId": "41f64f47-41b0-4dfc-ab45-1f3cf1187516",
      "quantity": 1      
    }
  ],
  "services": [
    {
      "serviceId": "3b1102cc-1551-47c9-aca0-9704d0311067",
      "quantity": 2      
    }
  ]
}


### Get Reservation
GET {{Api_HostAddress}}/Api/v1/Reservations(576c5a41-8faf-440f-9f50-afbc26a2dfa7)?$expand=Client,Packs,Equipments,Services
Content-Type: application/json

### Get All Reservation
GET {{Api_HostAddress}}/Api/v1/Reservations?$expand=Client,Payments,Quotes,Invoices,Services,Packs,Equipments
Content-Type: application/json

